### ISSUE TITLE
No instrument file generated if force_compile=False

### ISSUE THREAD

**Issue by shervin86** [PaNOSC-ViNYL/McStasScript#51]
When calling the backengine for the very first time, if the `force_compile` is False than the instrument is never generated and then it fails. If force_compile is False, a check of the existance of the instrument file should be performed to trigger generation and compilation at least once.

Example with the libpyvinyl instrument database:
```
from instrumentdatabaseapi import instrumentdatabaseapi as API
repo = API.Repository(local_repo=".")

instrument_name = "ThALES"
myinstrument = repo.load("ILL", instrument_name, "HEAD", "mcstas", dep=False)

myinstrument.calculators[myinstrument._calculator_name].settings(force_compile=False)
myinstrument.sim_neutrons(10000000)
myinstrument.run()
```

**Comment by mads-bertelsen** [comment]
Thanks for the report, that is indeed troublesome behaviour. Will make a small patch for this specific problem, and it will later be replaced by a better system that decides when to recompile based on hashes of the various parts of the instrument.
