### ISSUE TITLE
Feature request: Add openacc (GPU) acceleration option alongside MPI

### ISSUE THREAD

**Issue by willend** [PaNOSC-ViNYL/McStasScript#66]
A boolean flag to allow requesting `openacc` via https://mads-bertelsen.github.io/_autosummary/mcstasscript.helper.managed_mcrun.ManagedMcrun.html?highlight=mpi#mcstasscript.helper.managed_mcrun.ManagedMcrun.mpi

**Comment by mads-bertelsen** [comment]
Will do, but for now you can use the custom_flags in settings to add anything you want to the mcrun call.

instr.settings(custom_flags="--openacc")

Will also add a NeXus option that will set --format=NeXus.

**Comment by mads-bertelsen** [comment]
The settings now support openacc and NeXus keywords that default to False.
